import json
import os
from pathlib import Path

def get_config_dir_path() -> Path:
  root = Path(__file__).parent.parent
  config_dir = os.path.join(root, 'src/config')
  return config_dir

def create_config_cpp_file(json_data):
  lines = f"""
/*
  !!! THIS FILE IS GENERATED BY script/gen_config.py !!!
  !!! DO NOT EDIT THIS FILE MANUALLY !!!
*/

#include "dashboard.h"

static const char* raw_data = R"(
{json_data}
)";

namespace config {{
Dashboard::Dashboard() : raw_data_(raw_data) {{}}
}}  // namespace config
"""

  cpp_file_path = os.path.join(get_config_dir_path(), 'dashboard_autogen.cc')
  with open(cpp_file_path, 'w') as cpp_file:
    cpp_file.write(lines)

def create_qq_toml_file(json_data):
  json_obj = json.loads(json_data)

def main():
  json_file_path = os.path.join(get_config_dir_path(), 'config.json')
  with open(json_file_path, 'r') as json_file:
    json_data = json_file.read()
    create_config_cpp_file(json_data)
    # create_pl_toml_file(json_data)

if __name__ == "__main__":
  main()
